# Generated by Django 6.0.4 on 2026-05-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_image',
            field=models.ImageField(blank=True, null=True, upload_to='admin_images/'),
        ),
    ]
